### ISSUE TITLE
USER STORY: Edit or Delete Own Posts and Comments

### ISSUE THREAD

**Issue by Enzolita** [Enzolita/gamers-united#10]
As a **registered user,** I want to have the ability to edit or delete my own posts and comments.

## Acceptance Criteria:
- Acceptance Criteria 1: Users can access an "Edit" and "Delete" option for their own articles.
- Acceptance Criteria 2: Users can access an "Edit" and "Delete" option for their own comments.
- Acceptance Criteria 3: Deleted content is removed from public view.
- Acceptance Criteria 4: Edited content displays an edit timestamp.

## Tasks:
- [x] Implement "Edit" and "Delete" options for user posts.
- [x] Implement "Edit" and "Delete" options for user comments.
- [ ] Ensure edited content displays an edit timestamp.
