### ISSUE TITLE
Planning and Documentation

### ISSUE THREAD

**Issue by Enzolita** [Enzolita/gamers-united#2]
## Tasks
- [x] Create and write readme.md (Must do)
- [x] Design Database Schema (Should do)
- [x] Create the wireframes (Should do)
