### ISSUE TITLE
USER STORY: Search for Specific Games or Categories

### ISSUE THREAD

**Issue by Enzolita** [Enzolita/gamers-united#5]
As a visitor, I want to be able to  for specific games or categories.

## Acceptance Criteria:
- Acceptance Criteria 1: Users can access a search bar from any page on the blog.

## Tasks:
- [x] Implement a category filter.
- [ ] Create a search results page displaying relevant posts.
- [x] Implement filter options to refine search results.
