### ISSUE TITLE
USER STORY: Leave Comments and Take part in Discussions

### ISSUE THREAD

**Issue by Enzolita** [Enzolita/gamers-united#7]
As a registered user, I want to be able to leave comments on posts and take part in discussions with other fellow gamers.

## Acceptance Criteria:
- Acceptance Criteria 1: Registered users can leave comments on posts.
- Acceptance Criteria 2: Comments include usernames, and timestamps.
- Acceptance Criteria 3: Users can edit and delete their own comments.
- Acceptance Criteria 4: Users can reply to other users' comments to facilitate discussions.

## Tasks:
- [x]  Add a comment section to post detail page.
- [x]  Ensure comments display usernames, and timestamps.
- [x]  Implement the ability for users to edit and delete their comments.
